-- V1__create_hospital_schema.sql
-- Flyway migration: create initial hospital schema

CREATE TABLE IF NOT EXISTS doctors (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    specialty   VARCHAR(50)     NOT NULL,
    email       VARCHAR(100)    NOT NULL UNIQUE,
    license_no  VARCHAR(30)     NOT NULL UNIQUE,
    phone       VARCHAR(20),
    active      BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patients (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(50)     NOT NULL,
    last_name   VARCHAR(50)     NOT NULL,
    email       VARCHAR(100)    UNIQUE,
    phone       VARCHAR(20),
    birth_date  DATE            NOT NULL,
    blood_type  VARCHAR(5),
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointments (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id    BIGINT      NOT NULL REFERENCES doctors(id),
    patient_id   BIGINT      NOT NULL REFERENCES patients(id),
    scheduled_at TIMESTAMP   NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    notes        TEXT,
    created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
