spring:
  datasource:
    url: jdbc:h2:mem:taskdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
