-- V1: Fintech API Schema
-- week-11-jwt_y_oauth2

CREATE TABLE app_users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(50)  NOT NULL DEFAULT 'ROLE_USER',
    created_at TIMESTAMP
);

CREATE TABLE payments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount            DECIMAL(18, 2) NOT NULL,
    currency          VARCHAR(3)     NOT NULL,
    recipient_account VARCHAR(100)   NOT NULL,
    status            VARCHAR(50)    NOT NULL DEFAULT 'PENDING',
    owner_username    VARCHAR(100)   NOT NULL REFERENCES app_users(username),
    description       TEXT,
    created_at        TIMESTAMP
);
