CREATE TABLE posts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    content      TEXT         NOT NULL,
    author_email VARCHAR(255) NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

CREATE TABLE comments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content      TEXT         NOT NULL,
    author_email VARCHAR(255) NOT NULL,
    post_id      BIGINT       NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
