CREATE TABLE articles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255)  NOT NULL,
    content       TEXT,
    author_email  VARCHAR(255)  NOT NULL,
    category      VARCHAR(100)  NOT NULL,
    status        VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    published_at  TIMESTAMP
);
