-- V1: Task Management Schema
-- week-10-spring_security

CREATE TABLE app_users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(50)  NOT NULL DEFAULT 'ROLE_USER',
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP
);

CREATE TABLE tasks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    description    TEXT,
    status         VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    owner_username VARCHAR(100) NOT NULL REFERENCES app_users(username),
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP
);
